export const mockPaymentResponse = {
  resource: 'payment',
  id: 'tr_WDqYK6vllg',
  mode: 'test',
  createdAt: '2018-03-20T13:13:37+00:00',
  amount: {
    value: '10.00',
    currency: 'EUR',
  },
  description: 'Order #12345',
  method: null,
  metadata: {
    order_id: '12345',
  },
  status: 'open',
  isCancelable: false,
  locale: 'nl_NL',
  restrictPaymentMethodsToCountry: 'NL',
  expiresAt: '2018-03-20T13:28:37+00:00',
  details: null,
  profileId: 'pfl_QkEhN94Ba',
  orderId: 'ord_12345',
  sequenceType: 'oneoff',
  redirectUrl: 'https://webshop.example.org/order/12345/',
  webhookUrl: 'https://webshop.example.org/payments/webhook/',
};

export const mockPaidPayment = {
  resource: 'payment',
  id: 'tr_ncaPcAhuUV',
  mode: 'test',
  createdAt: '2018-03-20T13:13:37+00:00',
  amount: {
    value: '10.00',
    currency: 'EUR',
  },
  description: 'Order #12345',
  method: null,
  metadata: {
    order_id: '12345',
  },
  status: 'paid',
  isCancelable: false,
  locale: 'nl_NL',
  restrictPaymentMethodsToCountry: 'NL',
  expiresAt: '2018-03-20T13:28:37+00:00',
  details: null,
  profileId: 'pfl_QkEhN94Ba',
  orderId: 'ord_12345',
  sequenceType: 'oneoff',
  redirectUrl: 'https://webshop.example.org/order/12345/',
  webhookUrl: 'https://webshop.example.org/payments/webhook/',
  _embedded: {
    refunds: [
      {
        resource: 'refund',
        id: 're_8eP2Kzt9G9',
        amount: {
          value: '1.42',
          currency: 'EUR',
        },
        status: 'refunded',
        createdAt: '2022-01-19T08:42:47+00:00',
        description: 'Stort bestelling 18e822de-e148-4579-aaa4-e5bb08ac90e4 terug',
        metadata: null,
        orderId: 'ord_12345',
        paymentId: 'tr_fDBQGs7j87',
        settlementAmount: {
          value: '-1.42',
          currency: 'EUR',
        },
      },
    ],
  },
};
