version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mollie-commercetools-notification-module"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-oqts62h9ictg"
s3_prefix = "mollie-commercetools-notification-module"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
