AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  mollie-commercetools-notification-module

  Sample SAM Template for mollie-commercetools-notification-module
  
# Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst

Resources:
  MollieCommerceToolsNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      MemorySize: 128
      Timeout: 10
      CodeUri: build/
      Handler: index.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST
            RestApiId:
              Ref: MollieCommerceToolsNotificationFunctionAPI
      Environment:
        Variables:
          CT_MOLLIE_CONFIG: >-
            {"mollie":{"apiKey":"API_KEY"},"commercetools":{"authUrl":"AUTH_URL","clientId":"CLIENT_ID","clientSecret":"CLIENT_SECRET","host":"HOST","projectKey":"INTEGRATION"}}

  MollieCommerceToolsNotificationFunctionAPI:
    Type: AWS::Serverless::Api
    Properties:
        StageName: test
        DefinitionBody:
            swagger: 2.0
            info:
              title:
                Ref: AWS::StackName
            paths:
              "/":
                post:
                  x-amazon-apigateway-integration:
                    # The current implementation does not requires to transform the input from x-www-form-urlencoded in the API as we have decided to parse it in the application
                    # In case it is prefered to parse the payload in the API gateway more information can be found here:
                    # https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-mapping-template-reference.html
                    # https://blog.summercat.com/using-aws-lambda-and-api-gateway-as-html-form-endpoint.html
                    # https://github.com/willmanio/aws-api-gateway-bodyparser 
                    #requestTemplates:
                      #application/x-www-form-urlencoded: '{ "body" : "$input.body"}'
                    httpMethod: POST
                    type: aws_proxy
                    uri:
                      Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MollieCommerceToolsNotificationFunction.Arn}/invocations
                  responses: {}

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MollieCommerceToolsNotificationFunctionAPI:
    Description: "API Gateway endpoint URL for the function"
    Value: !Sub "https://${MollieCommerceToolsNotificationFunctionAPI}.execute-api.${AWS::Region}.amazonaws.com"
  MollieCommerceToolsNotificationFunction:
    Description: "MollieCommerceToolsNotificationFunction Lambda Function ARN"
    Value: !GetAtt MollieCommerceToolsNotificationFunction.Arn
  MollieCommerceToolsNotificationFunctionIamRole:
    Description: "Implicit IAM Role created forMollieCommerceToolsNotificationFunction function"
    Value: !GetAtt MollieCommerceToolsNotificationFunctionRole.Arn
