export const orderAuthorized = {
  resource: 'order',
  id: 'ord_v0wv0w',
  profileId: 'pfl_VtWA783A63',
  method: 'klarnapaylater',
  amount: { value: '2.24', currency: 'EUR' },
  status: 'authorized',
  isCancelable: true,
  metadata: { cartId: 'c9c76170-ff13-4bf8-b060-5caa84e94ec3' },
  createdAt: '2022-01-19T10:41:21+00:00',
  expiresAt: '2022-02-16T10:41:21+00:00',
  mode: 'test',
  locale: 'nl_NL',
  billingAddress: {
    streetAndNumber: 'Keizersgracht 126',
    postalCode: '1234AB',
    city: 'Amsterdam',
    country: 'NL',
    givenName: 'Piet',
    familyName: 'Mondriaan',
    email: 'coloured_square_lover@basicart.com',
  },
  shopperCountryMustMatchBillingCountry: false,
  orderNumber: '86ada6d8-2186-4cda-814a-17c5fe54221f',
  shippingAddress: {
    streetAndNumber: 'Keizersgracht 126',
    postalCode: '1234AB',
    city: 'Amsterdam',
    country: 'NL',
    givenName: 'Piet',
    familyName: 'Mondriaan',
    email: 'coloured_square_lover@basicart.com',
  },
  authorizedAt: '2022-01-19T10:48:34+00:00',
  redirectUrl: 'https://www.google.com/',
  webhookUrl: 'https://europe-west1-profound-yew-326712.cloudfunctions.net/dd-demo-notification',
  lines: [
    {
      resource: 'orderline',
      id: 'odl_1.nrs9fe',
      orderId: 'ord_v0wv0w',
      name: 'Apple',
      sku: '21345',
      type: 'physical',
      status: 'authorized',
      metadata: { cartLineItemId: '83bdde2b-99fb-4e60-a172-00e0b694be72' },
      isCancelable: true,
      quantity: 2,
      quantityShipped: 0,
      amountShipped: { value: '0.00', currency: 'EUR' },
      quantityRefunded: 0,
      amountRefunded: { value: '0.00', currency: 'EUR' },
      quantityCanceled: 0,
      amountCanceled: { value: '0.00', currency: 'EUR' },
      shippableQuantity: 2,
      refundableQuantity: 0,
      cancelableQuantity: 2,
      unitPrice: { value: '2.50', currency: 'EUR' },
      vatRate: '21.00',
      vatAmount: { value: '0.39', currency: 'EUR' },
      totalAmount: { value: '2.24', currency: 'EUR' },
      createdAt: '2022-01-19T10:41:21+00:00',
      discountAmount: { value: '2.76', currency: 'EUR' },
    },
    {
      resource: 'orderline',
      id: 'odl_1.ttslrg',
      orderId: 'ord_v0wv0w',
      name: 'Shipping - Standard Shipping',
      sku: null,
      type: 'shipping_fee',
      status: 'authorized',
      metadata: null,
      isCancelable: true,
      quantity: 1,
      quantityShipped: 0,
      amountShipped: { value: '0.00', currency: 'EUR' },
      quantityRefunded: 0,
      amountRefunded: { value: '0.00', currency: 'EUR' },
      quantityCanceled: 0,
      amountCanceled: { value: '0.00', currency: 'EUR' },
      shippableQuantity: 1,
      refundableQuantity: 0,
      cancelableQuantity: 1,
      unitPrice: { value: '40.00', currency: 'EUR' },
      vatRate: '21.00',
      vatAmount: { value: '0.00', currency: 'EUR' },
      totalAmount: { value: '0.00', currency: 'EUR' },
      createdAt: '2022-01-19T10:41:21+00:00',
      discountAmount: { value: '40.00', currency: 'EUR' },
    },
  ],
  _links: {
    self: {
      href: 'https://api.mollie.com/v2/orders/ord_v0wv0w',
      type: 'application/hal+json',
    },
    dashboard: {
      href: 'https://www.mollie.com/dashboard/org_12932188/orders/ord_v0wv0w',
      type: 'text/html',
    },
    documentation: {
      href: 'https://docs.mollie.com/reference/v2/orders-api/get-order',
      type: 'text/html',
    },
  },
  _embedded: undefined,
};
export const orderShipmentSuccess = {
  resource: 'shipment',
  id: 'shp_c1hs2y',
  orderId: 'ord_v0wv0w',
  createdAt: '2022-01-19T11:05:51+00:00',
  lines: [
    {
      resource: 'orderline',
      id: 'odl_1.nrs9fe',
      orderId: 'ord_v0wv0w',
      name: 'Apple',
      sku: '21345',
      type: 'physical',
      status: 'completed',
      metadata: { cartLineItemId: '83bdde2b-99fb-4e60-a172-00e0b694be72' },
      isCancelable: false,
      quantity: 2,
      unitPrice: { value: '2.50', currency: 'EUR' },
      vatRate: '21.00',
      vatAmount: { value: '0.39', currency: 'EUR' },
      totalAmount: { value: '2.24', currency: 'EUR' },
      createdAt: '2022-01-19T10:41:21+00:00',
      discountAmount: { value: '2.76', currency: 'EUR' },
    },
  ],
  _links: {
    self: {
      href: 'https://api.mollie.com/v2/orders/ord_v0wv0w/shipments/shp_c1hs2y',
      type: 'application/hal+json',
    },
    order: {
      href: 'https://api.mollie.com/v2/orders/ord_v0wv0w',
      type: 'application/hal+json',
    },
    documentation: {
      href: 'https://docs.mollie.com/reference/v2/shipments-api/create-shipment',
      type: 'text/html',
    },
  },
};
export const shipmentError = {
  status: 422,
  title: 'Unprocessable Entity',
  detail: 'This order cannot be shipped.',
  _links: {
    documentation: {
      href: 'https://docs.mollie.com/reference/v2/shipments-api/create-shipment',
      type: 'text/html',
    },
  },
};
